// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trawwcaudpwlfzyherkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYXd3Y2F1ZHB3bGZ6eWhlcmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTIzNTEsImV4cCI6MjA3NDEyODM1MX0.HLER0bhBIfZxlcnV_BjiLk6qgmUAhqJ0nmTxTKUMVrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});